openapi: 3.2.0
info:
  title: Hang Partner API (params in:formData) Activities API
  description: 'The Partner API allows you to request various resources that can power your loyalty program.


    © Hang 2023'
  version: 2023.09.07
  x-copyright: '&copy Hang 2023'
servers:
- url: /partner-api
security:
- ApiKeyAuth: []
tags:
- name: Activities
paths:
  /v2/program-memberships/{program_membership_id}/activities:
    post:
      tags:
      - Activities
      operationId: post_v2_program-memberships_program_membership_id_activities
      summary: Create a new activity
      parameters:
      - name: program_membership_id
        in: path
        required: true
        description: the program membership id
        schema:
          type: string
      responses:
        '200':
          description: Activity recorded for post-processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  idempotency_key:
                    type: string
                    description: idempotency key sent for activity
                additionalProperties: false
                required:
                - idempotency_key
      description: ''
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                activity[transaction_timestamp]:
                  type: number
                activity[value]:
                  type: string
                activity[activity_type_id]:
                  type: string
                idempotency_key:
                  type: string
                  description: used to prevent double-processing
                activity[line_items]:
                  type: array
                  items:
                    type: string
              required:
              - activity[transaction_timestamp]
              - activity[value]
              - activity[activity_type_id]
              - idempotency_key
          multipart/form-data:
            schema:
              type: object
              properties:
                activity[transaction_timestamp]:
                  type: number
                activity[value]:
                  type: string
                activity[activity_type_id]:
                  type: string
                idempotency_key:
                  type: string
                  description: used to prevent double-processing
                activity[line_items]:
                  type: array
                  items:
                    type: string
              required:
              - activity[transaction_timestamp]
              - activity[value]
              - activity[activity_type_id]
              - idempotency_key
  /v2/program-memberships/{program_membership_id}/activies/synchronous:
    post:
      tags:
      - Activities
      operationId: post_v2_program-memberships_program_membership_id_activies_synchronous
      summary: Create a new activity synchronously
      parameters:
      - name: program_membership_id
        in: path
        required: true
        description: the program membership id
        schema:
          type: string
      responses:
        '200':
          description: Activity recorded for post-processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  idempotency_key:
                    type: string
                    description: idempotency key sent for activity
                additionalProperties: false
                required:
                - idempotency_key
      description: ''
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                activity[transaction_timestamp]:
                  type: number
                activity[value]:
                  type: string
                activity[activity_type_id]:
                  type: string
                idempotency_key:
                  type: string
                  description: used to prevent double-processing
                activity[line_items]:
                  type: array
                  items:
                    type: string
              required:
              - activity[transaction_timestamp]
              - activity[value]
              - activity[activity_type_id]
              - idempotency_key
          multipart/form-data:
            schema:
              type: object
              properties:
                activity[transaction_timestamp]:
                  type: number
                activity[value]:
                  type: string
                activity[activity_type_id]:
                  type: string
                idempotency_key:
                  type: string
                  description: used to prevent double-processing
                activity[line_items]:
                  type: array
                  items:
                    type: string
              required:
              - activity[transaction_timestamp]
              - activity[value]
              - activity[activity_type_id]
              - idempotency_key
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
