swagger: '2.0'
info:
  title: Hang Partner API (params in:formData) Activities Programs API
  description: '

    <p>The Partner API allows you to request various resources that can power your loyalty program.</p>

    &copy Hang 2023'
  version: 2023.09.07
  x-copyright: '&copy Hang 2023'
basePath: /partner-api
schemes:
- https
consumes:
- application/x-www-form-urlencoded
- multipart/form-data
security:
- ApiKeyAuth: []
tags:
- name: Programs
paths:
  /programs/tiers:
    get:
      tags:
      - Programs
      consumes:
      - application/x-www-form-urlencoded
      - multipart/form-data
      operationId: get_programs_tiers
      summary: Fetch all tiers and corresponding benefits for the program linked to the API key used in the request.
      parameters: []
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              tiers:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the program tier object.
                    order:
                      type: number
                      description: The order in which the tier should be displayed.
                    tier_metric_minimum_threshold:
                      type: number
                      description: The minimum amount of points, or any tier metric (e.g. xp, points, stars, etc), the user must reach before being able to unlock the tier.
                    display_name:
                      type: string
                      description: The name of the tier.
                    marketing_benefit_text:
                      type: string
                      description: The marketing benefit text of the tier.
                    image_url:
                      type: string
                      description: The image associated to the tier.
                    benefits:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique identifier for the tier benefit object.
                        order:
                          type: string
                          description: The order in which the tier benefit should be displayed.
                        text:
                          type: string
                          description: The text of the tier benefit.
                        short_text:
                          type: string
                          description: The short text of the tier benefit.
                      additionalProperties: false
                      required:
                      - id
                      - order
                      - text
                      - short_text
                  additionalProperties: false
                  required:
                  - id
                  - order
                  - tier_metric_minimum_threshold
                  - display_name
                  - marketing_benefit_text
                  - image_url
                  - benefits
            additionalProperties: false
            required:
            - tiers
        '500':
          description: Something unexpected happened while trying to retrive the tier benefits.
      description: Tiers represent a status level that a user can achieve based on their activity within a loyalty program. Each tier has a minimum threshold that a user must reach before being able to unlock the tier.
  /v2/admin/program:
    get:
      tags:
      - Programs
      consumes:
      - application/x-www-form-urlencoded
      - multipart/form-data
      operationId: get_v2_admin_program
      summary: Endpoint to return program information using the current JWT.
      parameters: []
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              program:
                type: object
                properties:
                  should_use_progression_v2:
                    type: boolean
                    description: Boolean flag indicating if the program is using v2 progression.
                additionalProperties: false
                required:
                - should_use_progression_v2
            additionalProperties: false
            required:
            - program
      description: ''
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
