swagger: '2.0'
info:
  title: Hang Partner API (params in:formData) Activities Program Tiers API
  description: '

    <p>The Partner API allows you to request various resources that can power your loyalty program.</p>

    &copy Hang 2023'
  version: 2023.09.07
  x-copyright: '&copy Hang 2023'
basePath: /partner-api
schemes:
- https
consumes:
- application/x-www-form-urlencoded
- multipart/form-data
security:
- ApiKeyAuth: []
tags:
- name: Program Tiers
paths:
  /v2/admin/program-tiers:
    get:
      tags:
      - Program Tiers
      consumes:
      - application/x-www-form-urlencoded
      - multipart/form-data
      operationId: get_v2_admin_program-tiers
      summary: Get all program tiers
      parameters: []
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              tiers:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the program tier object.
                    order:
                      type: number
                      description: The order in which the tier should be displayed.
                    tier_metric_minimum_threshold:
                      type: number
                      description: The minimum amount of points, or any tier metric (e.g. xp, points, stars, etc), the user must reach before being able to unlock the tier.
                    display_name:
                      type: string
                      description: The name of the tier.
                    marketing_benefit_text:
                      type: string
                      description: The marketing benefit text of the tier.
                    image_url:
                      type: string
                      description: The image associated to the tier.
                  additionalProperties: false
                  required:
                  - id
                  - order
                  - tier_metric_minimum_threshold
                  - display_name
                  - marketing_benefit_text
                  - image_url
            additionalProperties: false
            required:
            - tiers
      description: Tiers represent a status level that a user can achieve based on their activity within a loyalty program. Each tier has a minimum threshold that a user must reach before being able to unlock the tier.
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
