openapi: 3.2.0
info:
  title: Hang Partner API (params in:formData) Redemptions API
  description: 'The Partner API allows you to request various resources that can power your loyalty program.


    © Hang 2023'
  version: 2023.09.07
  x-copyright: '&copy Hang 2023'
servers:
- url: /partner-api
security:
- ApiKeyAuth: []
tags:
- name: Redemptions
paths:
  /wallets/{wallet_address}/redemptions:
    get:
      tags:
      - Redemptions
      operationId: get_wallets_wallet_address_redemptions
      summary: Retrieve redemption history, if any, for a given wallet_address
      parameters:
      - name: wallet_address
        in: path
        required: true
        description: the wallet address
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redemptions:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: number
                          description: when the reward was redeemed, in epoch seconds
                        token_id:
                          type: string
                          description: the token id of the reward associated with the redemption
                        description:
                          type: string
                          description: the description of the reward redeemed
                        code:
                          type: string
                          description: the code used to redeem the reward
                      additionalProperties: false
                      required:
                      - date
                      - token_id
                      - description
                      - code
                additionalProperties: false
                required:
                - redemptions
      description: Invoke this endpoint to return an array of rewards that were redeemed while associated with a specified wallet address.
    post:
      tags:
      - Redemptions
      operationId: post_wallets_wallet_address_redemptions
      summary: Generate a redemption code for a given reward by providing the wallet_address…
      parameters:
      - name: wallet_address
        in: path
        required: true
        description: the wallet address
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redemption:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: redemption uuid
                      code:
                        type: string
                        description: redemption code
                      promo_code:
                        type: string
                        description: promo code of the redemption
                      state:
                        type: string
                        description: state of the redemption
                      expires_at:
                        type: number
                        description: the time the redemption expires, in epoch seconds
                    additionalProperties: false
                    required:
                    - uuid
                    - code
                    - promo_code
                    - state
                    - expires_at
                additionalProperties: false
                required:
                - redemption
        '401':
          description: Could not generate code due to wallet_address not owning token.
        '404':
          description: Could not generate code due to invalid token_id, or reward_id.
      description: Utilize this endpoint to generate a redemption code for a given reward.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reward_id:
                  type: string
                  description: the reward uuid
                token_id:
                  type: string
                  description: the token id
              required:
              - reward_id
              - token_id
          multipart/form-data:
            schema:
              type: object
              properties:
                reward_id:
                  type: string
                  description: the reward uuid
                token_id:
                  type: string
                  description: the token id
              required:
              - reward_id
              - token_id
  /redemptions/{redemption_uuid}/redeem:
    post:
      tags:
      - Redemptions
      operationId: post_redemptions_redemption_uuid_redeem
      summary: Redeem a redemption code providing the uuid for the redemption record
      parameters:
      - name: redemption_uuid
        in: path
        required: true
        description: the uuid for the redemption code
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redemption:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: redemption uuid
                      code:
                        type: string
                        description: redemption code
                      promo_code:
                        type: string
                        description: promo code of the redemption
                      state:
                        type: string
                        description: state of the redemption (redeemed, initiated, denied)
                      expires_at:
                        type: number
                        description: the time the redemption expires, in epoch seconds
                    additionalProperties: false
                    required:
                    - uuid
                    - code
                    - promo_code
                    - state
                    - expires_at
                additionalProperties: false
                required:
                - redemption
        '404':
          description: Redemption code not found for given uuid.
        '422':
          description: The reward is not redeemable.
      description: Utilize this endpoint to redeem a redemption code via its corresponding uuid
  /v2/program-memberships/{program_membership_id}/redemptions:
    get:
      tags:
      - Redemptions
      operationId: get_v2_program-memberships_program_membership_id_redemptions
      summary: Retrieve redemption history, if any, for a given program membership
      parameters:
      - name: program_membership_id
        in: path
        required: true
        description: the program membership id
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redemptions:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: number
                          description: when the reward was redeemed, in epoch seconds
                        description:
                          type: string
                          description: the description of the reward redeemed
                        code:
                          type: string
                          description: the code used to redeem the reward
                      additionalProperties: false
                      required:
                      - date
                      - description
                      - code
                additionalProperties: false
                required:
                - redemptions
      description: Invoke this endpoint to return an array of rewards that were redeemed while associated with a specified program membership.
    post:
      tags:
      - Redemptions
      operationId: post_v2_program-memberships_program_membership_id_redemptions
      summary: Generate a redemption code for a given reward by providing the…
      parameters:
      - name: program_membership_id
        in: path
        required: true
        description: the program membership id
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redemption:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: redemption uuid
                      code:
                        type: string
                        description: redemption code
                      promo_code:
                        type: string
                        description: promo code of the redemption
                      state:
                        type: string
                        description: state of the redemption
                      expires_at:
                        type: number
                        description: the time the redemption expires, in epoch seconds
                    additionalProperties: false
                    required:
                    - uuid
                    - code
                    - promo_code
                    - state
                    - expires_at
                additionalProperties: false
                required:
                - redemption
        '404':
          description: Could not generate code due to invalid program_membership_id or reward_id.
      description: Utilize this endpoint to generate a redemption code for a given reward.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reward_id:
                  type: string
                  description: the reward uuid
              required:
              - reward_id
          multipart/form-data:
            schema:
              type: object
              properties:
                reward_id:
                  type: string
                  description: the reward uuid
              required:
              - reward_id
  /v2/redemptions/{redemption_uuid}/redeem:
    post:
      tags:
      - Redemptions
      operationId: post_v2_redemptions_redemption_uuid_redeem
      summary: Redeem a redemption code providing the uuid for the redemption record
      parameters:
      - name: redemption_uuid
        in: path
        required: true
        description: the uuid for the redemption code
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redemption:
                    type: object
                    properties:
                      uuid:
                        type: string
                        description: redemption uuid
                      code:
                        type: string
                        description: redemption code
                      promo_code:
                        type: string
                        description: promo code of the redemption
                      state:
                        type: string
                        description: state of the redemption (redeemed, initiated, denied)
                      expires_at:
                        type: number
                        description: the time the redemption expires, in epoch seconds
                    additionalProperties: false
                    required:
                    - uuid
                    - code
                    - promo_code
                    - state
                    - expires_at
                additionalProperties: false
                required:
                - redemption
        '404':
          description: Redemption code not found for given uuid.
        '422':
          description: The reward is not redeemable.
      description: Utilize this endpoint to redeem a redemption code via its corresponding uuid
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
